<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Unison</string>
    <key>scopeName</key>
    <string>source.u</string>
    <key>fileTypes</key>
    <array>
      <string>u</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#boolean</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numeric</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#text</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#match-with</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#control</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#def</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#forall</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#arrow</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#eof-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line-comment</string>
          </dict>
        </array>
      </dict>
      <key>boolean</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.true.unison</string>
            <key>match</key>
            <string>true</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.false.unison</string>
            <key>match</key>
            <string>false</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#float</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#int</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#nat</string>
          </dict>
        </array>
      </dict>
      <key>text</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.unison</string>
        <key>begin</key>
        <string>(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.unison</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.unison</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>match-with</key>
      <dict>
        <key>match</key>
        <string>(\s|^)(cases|match|with)(?=\s|$)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.match.unison</string>
          </dict>
        </dict>
      </dict>
      <key>control</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(if|then|else|and|or)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.unison</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(&amp;&amp;|\|\|)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.unison</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>def</key>
      <dict>
        <key>match</key>
        <string>([^\r\n\t\f\v \"]+)\s*(:)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.unison</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.colon.unison</string>
          </dict>
        </dict>
      </dict>
      <key>forall</key>
      <dict>
        <key>match</key>
        <string>(\s|^|\b)(forall|∀)(\s|$|\b)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.forall.unison</string>
          </dict>
        </dict>
      </dict>
      <key>arrow</key>
      <dict>
        <key>match</key>
        <string>(-&gt;)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.arrow.unison</string>
          </dict>
        </dict>
      </dict>
      <key>eof-comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^\s+)?(?=---)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.unison</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.block.eof.unison</string>
                <key>begin</key>
                <string>(?&lt;!-)---(?:(?!-)|(?=---))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.unison</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\z</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>line-comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^\s+)?(?=--)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.unison</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.double-dash.unison</string>
                <key>begin</key>
                <string>(?&lt;!-)--(?:(?!-)|(?=--))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.unison</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>float</key>
      <dict>
        <key>match</key>
        <string>([^+\-\w\d]|^)([+-]?\d+\.\d*)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.unison</string>
          </dict>
        </dict>
      </dict>
      <key>int</key>
      <dict>
        <key>match</key>
        <string>([^\w\d]|^)([+-]\d+)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.integer.signed.unison</string>
          </dict>
        </dict>
      </dict>
      <key>nat</key>
      <dict>
        <key>match</key>
        <string>\b(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.integer.unsigned.unison</string>
          </dict>
        </dict>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.unison</string>
        <key>match</key>
        <string>\\"</string>
      </dict>
    </dict>
  </dict>
</plist>